name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Build the app
        run: |
          echo "Building the app"
          make build

      - name: Test the app
        run: |
          echo "Testing the app"
          make test

      - name: Check with linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
